[package]
name = "qdrant-catch-me-if-you-can"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
futures = "0.3"
qdrant-client = "1.4.0"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
tonic = "0.9.2"
